import type { Metadata } from "next"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import "./globals.css"
import { prisma } from "@/lib/prisma"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"], // выбери нужные подмножества
  variable: "--font-inter", // если хочешь использовать CSS-переменную
  display: "swap", // улучшает загрузку
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // const date = new Date()
  // const orders = await prisma.orders.findMany({
  //   where: { order_date: date },
  // })
  // console.log(orders)
  return (
    <html className="" lang="en">
      <body className={`${inter.className} antialiased mx-1 text-sm `}>
        {children}
      </body>
    </html>
  )
}
