import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import ForceLightTheme from "./components/OverrideTHThemes"
import { prisma } from "@/lib/prisma"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // const date = new Date()
  // const orders = await prisma.orders.findMany({
  //   where: { order_date: date },
  // })
  // console.log(orders)
  return (
    <html className="" lang="en">
      <>
        <ForceLightTheme />
      </>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  font-light  `}
      >
        {children}
      </body>
    </html>
  )
}
